# Generated by Django 4.2.1 on 2023-06-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_options_alter_products_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_by',
        ),
    ]
