# Generated by Django 4.2.1 on 2023-06-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_products_options_alter_products_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
