# Generated by Django 4.2.1 on 2023-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_quatity_orderproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
