# Generated by Django 4.2.1 on 2023-06-19 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_address2', models.CharField(max_length=255)),
                ('shipping_country', models.CharField(max_length=255)),
                ('shipping_zip', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_address2', models.CharField(max_length=255)),
                ('billing_country', models.CharField(max_length=255)),
                ('billing_zip', models.CharField(max_length=255)),
                ('payment_option', models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
